import { createBrowserClient } from '@supabase/ssr';
import { createClient } from '@supabase/supabase-js';

const supabaseUrl = process.env.NEXT_PUBLIC_SUPABASE_URL;
const supabaseKey = process.env.SUPABASE_SERVICE_ROLE_KEY || process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY;

if (!supabaseUrl || !supabaseKey) {
    console.error('Missing Supabase environment variables');
}

export const supabase = createClient(supabaseUrl!, supabaseKey!);

export function createSupabaseClient() {
    return createClient(supabaseUrl!, supabaseKey!);
}

export function getSupabaseForBrowser() {
    return createBrowserClient(process.env.NEXT_PUBLIC_SUPABASE_URL!, process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
}

/*
CREATE TABLE public."Contact" (
    "id" integer generated by default as identity primary key,
    "createdAt" timestamp with time zone not null default now(),
    "fullname" text null,
    "email" text null,
    "phone" text null,
    "userNote" text null,
    "isContacted" boolean null,
    "ourNote" text null,
    "userAgent" text null,
    "ipAddress" inet null,
    "referrer" text null,
    "appName" text null,
    "placeName" text null,
    "url" text null
) TABLESPACE pg_default;
*/
