/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../components/Items/Item';
import { effectToRef } from '../../../utils/Drawing/effectToRef';
import { birdsCzEffect } from '../../../utils/Drawing/projectsEffectsLibrary';
import background from '../Pavol_Hejn_birds_3eee9b48-0331-462d-b11d-367626cf028c.png';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-projects-library
 */
export function BirdsCzProject() {
    return (
        <a href="#" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Birds.cz</Item.Title>
                <Item.Description>
                    <p>A variety of projects focusing on citizenship science for the Czech Society of Ornithology</p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(birdsCzEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="@@@" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
