/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../components/Items/Item';
import { effectToRef } from '../../../utils/Drawing/effectToRef';
import { virtualAndAugmentedRealityEffect } from '../../../utils/Drawing/projectsEffectsLibrary';
import background from '../drawing-in-vr.png';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-projects-library
 */
export function VirtualAndAugmentedRealityProject() {
    return (
        <a href="#!!!" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Virtual and augmented reality</Item.Title>
                <Item.Description>
                    <p>
                        I have worked on multiple projects for virtuen augmented reality imosu Ambassador of association
                        of virtual
                    </p>
                    <p>I have presented this DevConf, CzechVRFest, Hackuj Stát</p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(virtualAndAugmentedRealityEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="@@@" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
