/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../src/components/Items/Item';
import { effectToRef } from '../../../src/utils/Drawing/effectToRef';
import { hEduEffect } from '../../../src/utils/Drawing/projectsEffectsLibrary';
import background from './outline.svg';

/**
 * Presentation of project H-edu
 *
 * @see /public/projects/projects.md
 * @generated by generate-projects-library
 */
export function HEduProject() {
    return (
        <a href="https://www.h-edu.cz/" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>H-edu</Item.Title>
                <Item.Description>
                    <p>An online platform for schools and teachers with interactive materials and tools.</p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(hEduEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="Triangle for counting" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
