/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { Item } from '../../../components/Items/Item';
import { effectToRef } from '../../../utils/Drawing/effectToRef';
import { yourProjectEffect } from '../../../utils/Drawing/projectsEffectsLibrary';
import background from './outline.svg';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-projects-library
 */
export function YourProjectProject() {
    return (
        <a href="https://pavolhejny.com/documents/projects.html" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Your project</Item.Title>
                <Item.Description>
                    <p>I will be happy kick off your project</p>
                    <p>What I offer?</p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(yourProjectEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="@@@" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
