/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../components/Items/Item';
import { effectToRef } from '../../../utils/Drawing/effectToRef';
import { birdsEffect } from '../../../utils/Drawing/projectsEffectsLibrary';
import background from './outline.svg';

/**
 * Presentation of project Birds
 *
 * @see /public/projects/projects.md
 * @generated by generate-projects-library
 */
export function BirdsProject() {
    return (
        <a href="#" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Birds</Item.Title>
                <Item.Description>
                    <p>
                        A series of citizen science projects for the{' '}
                        <a href="https://www.birdlife.cz/">Czech Society for Ornithology</a>.
                    </p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(birdsEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="Bird outline" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
