/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { Item } from '../../../src/components/Items/Item';
import { effectToRef } from '../../../src/utils/Drawing/effectToRef';
import { modulesEffect } from '../../../src/utils/Drawing/projectsEffectsLibrary';
import background from './placeholder.svg';

/**
 * Presentation of project Modules
 *
 * @see /public/projects/projects.md
 * @generated by generate-projects-library
 */
export function ModulesProject() {
    return (
        <a href="https://github.com/collboard/modules-sdk" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Modules</Item.Title>
                <Item.Image>
                    <div
                        ref={effectToRef(modulesEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="Pseudo-USB gadget" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
