/**
 * 🏭 GENERATED WITH 🖼️ Generate hackings library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-hackings-library
 */
export function WebVrHacking() {
    return <Item>!!!## Web VR</Item>;
}
