name: Generate

on:
    workflow_dispatch:
    schedule:
        - cron: '11 11 * * *'

jobs:
    generate:
        name: Generate
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm ci

            - name: Generate projects
              run: ts-node ./scripts/generate-projects/generate-projects.ts --commit
