/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { forTime } from 'waitasecond';
import { Vector } from 'xyzt';
import { Item } from '../../../components/Items/Item';
import { Drawing } from '../../../utils/Drawing/Drawing';
import background from '../whiteboard.png';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-projects-library
 */
export function CollboardProject() {
    return (
        <a
            href="#"
            target="_blank"
            rel="noreferrer"
            ref={(element) => {
                // !!! Also work on mobile
                // TODO: To separate util addFoooInteractivity

                if (element === null) {
                    return;
                }

                let drawing: Drawing | null = null;

                element.addEventListener('pointerenter', (event) => {
                    if (drawing) {
                        return;
                    }

                    drawing = new Drawing().addPoint(Vector.fromObject(event, ['pageX', 'pageY']));
                });

                window.addEventListener('pointermove', (event) => {
                    if (!drawing) {
                        return;
                    }

                    drawing.addPoint(Vector.fromObject(event, ['pageX', 'pageY']));
                });

                element.addEventListener('pointerleave', async (event) => {
                    // TODO: Add more events like leaving whole document / loose of focus /...

                    if (!drawing) {
                        return;
                    }

                    await forTime(100);

                    // TODO: Make here a propper queue
                    if (drawing && !drawing.isDestroyed) {
                        /* not await */ drawing.destroy();
                        drawing = null;
                    }
                });
            }}
        >
            <Item>
                <Item.Title>Collboard</Item.Title>
                <Item.Description>
                    <p>
                        Virtual online collaborative whiteboard started during the the initial week of the
                        pandemic-induced lockdown.
                    </p>
                </Item.Description>
                <Item.Image>
                    <div
                        style={{
                            backgroundImage: `url(${background.src})`,
                            backgroundSize: 'cover',
                            backgroundPosition: '50% 30%',
                            backgroundRepeat: 'no-repeat',
                            width: '100%',
                            height: '100%',
                        }}
                    />
                    {/* <Image alt="@@@" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
