/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../components/Items/Item';
import background /* <- TODO: Put filename into this import name .replace(/.[a-z0-9]+$/, '') */ from '../xyzt.png';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-projects-library
 */
export function LibrariesProject() {
    return (
        <Item>
            <Item.Title>Libraries</Item.Title>
            <Item.Description>
                {/* TODO: !!! Text should be selectable even inside of <a> */}
                <p>
                    I am working on several OpenSource libraries like
                    <a href="https://github.com/hejny/xyzt">vector library xyzt</a>,
                    <a href="https://github.com/hejny/locate-app">locating apps in your system</a>,
                    <a href="https://github.com/hejny/waitasecond">waitasecond to supercharge the promises</a>,
                    <a href="https://github.com/hejny/spacetrim">trimming from all 4 directions</a>,
                    <a href="https://github.com/hejny/destroyable">working with destroyable objects</a>
                    or see <a href="https://github.com/hejny?tab=repositories">my GitHub repositories</a>.
                </p>
            </Item.Description>
            <Item.Image>
                <Image alt="" src={background} draggable="false" />
            </Item.Image>
        </Item>
    );
}
