/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { Item } from '../../../components/Items/Item';
import background /* <- TODO: Put filename into this import name .replace(/.[a-z0-9]+$/, '') */ from '../webvr.jpg';

/**
 * !!!
 *
 * @see !!!
 * @generated by generate-projects-library
 */
export function WebVrProject() {
    return (
        <Item>
            <Item.Title>Web VR</Item.Title>
            <Item.Description>
                {/* TODO: !!! Text should be selectable even inside of <a> */}
                <p>DevConf, CzechVRFest, Hackuj Stát</p>
            </Item.Description>
            <Item.Image>
                <div
                    style={{
                        backgroundImage: background.src,
                        backgroundSize: 'cover',
                        backgroundRepeat: 'no-repeat',
                        aspectRatio: '2/3',
                    }}
                ></div>
            </Item.Image>
        </Item>
    );
}
