/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../components/Items/Item';
import { effectToRef } from '../../../utils/Drawing/effectToRef';
import { czechEventsEffect } from '../../../utils/Drawing/projectsEffectsLibrary';
import background from './Pavol_Hejn_Simple_pen_sketch_of_A_have_big_interest_in_Czech_Te_62acce49-a9db-4d36-9199-d606551f463c.svg';

/**
 * Presentation of project Czech.events
 *
 * @see /public/projects/projects.md
 * @generated by generate-projects-library
 */
export function CzechEventsProject() {
    return (
        <a href="https://czech.events/" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Czech.events</Item.Title>
                <Item.Description>
                    <p>
                        Stay updated on the latest tech events in Czechia with the Czech Tech Community Newsletter. I
                        bring expertise from organizing, speaking at, and mentoring events.
                    </p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(czechEventsEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="Meetup" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
