/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { Item } from '../../../src/components/Items/Item';
import { Translate } from '../../../src/components/Translate/Translate';
// import { effectToRef } from '../../../src/utils/Drawing/effectToRef';
// import { promptbookEffect } from '../../../src/utils/Drawing/projectsEffectsLibrary';
import pavolHejnIsometricGameAsAColoringBookBlackAndWhiteIlB1cde821101c4d3fAd5b1f345d4009c5 from './Pavol_Hejn_isometric_game_as_a_coloring_book_black_and_white_il_b1cde821-101c-4d3f-ad5b-1f345d4009c5.svg';

/**
 * Presentation of project Promptbook
 *
 * @see /public/projects/promptbook/promptbook.en.md
 * @see /public/projects/promptbook/promptbook.cs.md
 * @generated by generate-projects-library
 */
export function PromptbookProject() {
    return (
        <a href="https://ptbk.io/" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>
                    <Translate locale="en">Promptbook</Translate>
                    <Translate locale="cs">Promptbook</Translate>
                </Item.Title>
                <Item.Description>
                    <Translate locale="en">
                        <p>Persistent AI agents with goals, knowledge, rules, and company context</p>
                    </Translate>
                    <Translate locale="cs">
                        <p>Persistentní AI agenti pro cíle, znalosti, pravidla a firemní kontext</p>
                    </Translate>
                </Item.Description>
                <Item.Image>
                    <div
                        // ref={effectToRef(promptbookEffect)}
                        style={{
                            backgroundImage: `url(${pavolHejnIsometricGameAsAColoringBookBlackAndWhiteIlB1cde821101c4d3fAd5b1f345d4009c5.src})`,
                        }}
                    />
                    {/* <Image alt="Tile of online game" src={background} draggable="false" placeholder="blur" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
