/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { Item } from '../../../src/components/Items/Item';
import { effectToRef } from '../../../src/utils/Drawing/effectToRef';
import { czechEventsEffect } from '../../../src/utils/Drawing/projectsEffectsLibrary';
import background from './Pavol_Hejny_Coloring_book_black_and_white_illustration_outline__f429b7c9-7d63-4df8-9f95-07158107df10.svg';

/**
 * Presentation of project Czech.events
 *
 * @see /public/projects/projects.md
 * @generated by generate-projects-library
 */
export function CzechEventsProject() {
    return (
        <a href="https://czech.events/" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Czech.events</Item.Title>
                <Item.Description>
                    <p>Newsletter of the most interesting IT &amp; Startup events in Czechia</p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(czechEventsEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="Meetup" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
