import { Inter } from '@next/font/google';
import Head from 'next/head';
import { Cave } from '../components/Cave/Cave';
import { Services } from '../components/Services/Services';
import styles from './index.module.css';

// !!! What is this - inter/Inter
const inter = Inter({ subsets: ['latin'] });

// !!! The best way to import the fonts

export default function Home() {
    return (
        // TODO: !!! Change from boilerplate
        <>
            <Head>
                <title>🧙‍♂️ Rapid prototyping wizard</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <div className={styles.page}>
                <div className={styles.cave}>
                    <Cave />
                </div>

                <div className={styles.content}>
                    {/* TODO: Make as <Component/> */}
                    <h1>Wizard</h1>

                    {/* TODO: Make as <Component/> */}
                    <p>
                        AI, Neural networks, VR/AR, WebGL, WebVR, Webassembly, WebSockets. Bitcoin, Ethereum, Cardano,
                        Crypto, Smart contracts, Web3, ...
                    </p>

                    <Services />
                </div>
            </div>
        </>
    );
}

/**
 * TODO: !!! Use somewhere <main> element
 * TODO: !!! Split into components
 * TODO: !!! Custom 404 page
 */
