import Head from 'next/head'
import Image from 'next/image'

import { Inter } from '@next/font/google'
import styles from '../styles/Home.module.css'
import caveOfIdeasImage from '../public/wallpapers/cave-of-ideas.webp'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    // TODO: !!! Change from boilerplate 
    <>
      <Head>
        <title>🧙‍♂️ Rapid prototyping wizard</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main style={{
        backgroundImage: `url(${caveOfIdeasImage.src})`,
        backgroundSize: `cover`,
        backgroundPosition: `10% bottom`,
        backgroundRepeat: `no-repeat`,
        minHeight: `100vh`,
        padding: 10,
        display: 'grid',
        gridTemplateRows: `1fr 1fr 1fr`,
        gridTemplateColumns: `1fr 1fr 1fr`,
      }}>
        <h1 style={{
          // !!! Should be font in "

          gridRowStart: 1,
          gridRowEnd: 4,
          gridColumnStart: 1,
          gridColumnEnd: 4,
          //textAlign:'center',


          fontFamily: '"PassionsConflict", Helvetica Neue',
          fontSize: '70px',
          bottom: 0,
          // width: 100,
        }}>
          Rapid
          prototyping
          wizard
          {/*🧙‍♂️*/}
        </h1>
        {/*<Image alt="Cave of ideas" src={caveOfIdeasImage} />*/}
        
      </main>
    </>
  )
}
