/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import Image from 'next/image';
import { Item } from '../../../src/components/Items/Item';
import { effectToRef } from '../../../src/utils/Drawing/effectToRef';
import { townsEffect } from '../../../src/utils/Drawing/projectsEffectsLibrary';
import background from './Pavol_Hejn_isometric_game_as_a_coloring_book_black_and_white_il_b1cde821-101c-4d3f-ad5b-1f345d4009c5.svg';

/**
 * Presentation of project Towns
 *
 * @see /public/projects/projects.md
 * @generated by generate-projects-library
 */
export function TownsProject() {
    return (
        <a href="https://towns.cz/" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>Towns</Item.Title>
                <Item.Description>
                    <p>A browser-based online game where players can build their own cities and worlds.</p>
                </Item.Description>
                <Item.Image>
                    <div
                        ref={effectToRef(townsEffect)}
                        style={{
                            backgroundImage: `url(${background.src})`,
                        }}
                    />
                    {/* <Image alt="Tile of online game" src={background} draggable="false" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
