/**
 * 🏭 GENERATED WITH 🖼️ Generate projects library
 * ⚠️ Warning: Do not edit by hand, all changes will be lost on next execution!
 *    If you want to edit this file:
 *      - Change @generated to @not-generated
 *      - And remove this warning
 *    Then the file will not be re-generated automatically
 */

import { Item } from '../../../src/components/Items/Item';
import { Translate } from '../../../src/components/Translate/Translate';
// import { effectToRef } from '../../../src/utils/Drawing/effectToRef';
// import { ainautesEffect } from '../../../src/utils/Drawing/projectsEffectsLibrary';
import pavolHejnyColoringBookBlackAndWhiteIllustrationOutlineF429b7c97d634df89f9507158107df10 from './Pavol_Hejny_Coloring_book_black_and_white_illustration_outline__f429b7c9-7d63-4df8-9f95-07158107df10.svg';

/**
 * Presentation of project Ainautes
 *
 * @see /public/projects/ainautes/ainautes.en.md
 * @see /public/projects/ainautes/ainautes.cs.md
 * @generated by generate-projects-library
 */
export function AinautesProject() {
    return (
        <a href="https://www.ainautes.com/" target="_blank" rel="noreferrer">
            <Item>
                <Item.Title>
                    <Translate locale="en">Ainautes</Translate>
                    <Translate locale="cs">Ainautes</Translate>
                </Item.Title>
                <Item.Description>
                    <Translate locale="en">
                        <p>A group of people who navigate you through the seas of artificial intelligence.</p>
                    </Translate>
                    <Translate locale="cs">
                        <p>Skupina lidí, kteří vás navigují v rozbouřeném moři umělé inteligence.</p>
                    </Translate>
                </Item.Description>
                <Item.Image>
                    <div
                        // ref={effectToRef(ainautesEffect)}
                        style={{
                            backgroundImage: `url(${pavolHejnyColoringBookBlackAndWhiteIllustrationOutlineF429b7c97d634df89f9507158107df10.src})`,
                        }}
                    />
                    {/* <Image alt="Meetup" src={background} draggable="false" placeholder="blur" /> */}
                </Item.Image>
            </Item>
        </a>
    );
}
