name: Deploy the page

on:
    push:
        tags:
            - 'v*'

jobs:
    deploy:
        name: Deploy the page
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            # restore!!> - name: Generate projects library
            # restore!!>   run: ts-node ./scripts/generate-projects-library/generate-projects-library.ts --commit

            # restore!!> - name: Generate wallpapers library
            # restore!!>   run: ts-node ./scripts/generate-projects-library/generate-wallpapers-library.ts --commit

            # restore!!> - name: Generate patterns library
            # restore!!>   run: ts-node ./scripts/generate-projects-library/generate-patterns-library.ts --commit

            - name: Lint
              run: npm run lint

            - name: Unit test
              run: npm run test-unit

            - name: Integration test
              run: npm run test-integration

            - name: Build
              run: npm run build
              env:
                  # !! Remove openssl-legacy-provider ACRY
                  NODE_OPTIONS: --openssl-legacy-provider

            - name: Configurate GIT
              run: |
                  git config --global user.email "me@pavolhejny.com"
                  git config --global user.name "hejny"

            - name: Deploy on GitHub pages
              run: npx gh-pages --dotfiles --dist ./out --repo https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
