name: Deploy the page

on:
    push:
        tags:
            - 'v*'

jobs:
    test:
        name: Test + Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Unit test
              run: npm run test-unit
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

    deploy:
        name: Publish on Github pages
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Generate projects library
              run: ts-node ./scripts/generate-projects-library/generate-projects-library.ts --commit

            - name: Generate wallpapers library
              run: ts-node ./scripts/generate-projects-library/generate-wallpapers-library.ts --commit

            - name: Generate patterns library
              run: ts-node ./scripts/generate-projects-library/generate-patterns-library.ts --commit

            - name: Build
              run: npm run build
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

            - name: Configurate GIT
              run: |
                  git config --global user.email "me@pavolhejny.com"
                  git config --global user.name "hejny"

            - name: Deploy on GitHub pages
              run: npx gh-pages --dotfiles --dist ./out --repo https://x-access-token:${{secrets.GITHUB_TOKEN}}@github.com/${GITHUB_REPOSITORY}.git
