name: Publish new version

on:
    push:
        tags:
            - 'v*'

jobs:
    test:
        name: Test + Lint
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Lint
              run: npm run lint

            - name: Test
              run: npm run test
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

    publish-github:
        name: Publish on Github pages
        needs: test
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v1
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Build
              run: npm run build
              env:
                  NODE_OPTIONS: --openssl-legacy-provider

            - name: Deploy
              run: npm run deploy
              env:
                  NODE_OPTIONS: --openssl-legacy-provider