name: Test

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    test:
        name: Test TSNode
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 17

            - name: Install dependencies
              run: npm ci

            - name: Generate projects library
              run: ts-node ./scripts/generate-projects-library/generate-projects-library.ts --commit

            - name: Generate wallpapers library
              run: ts-node ./scripts/generate-projects-library/generate-wallpapers-library.ts --commit

            - name: Generate patterns library
              run: ts-node ./scripts/generate-projects-library/generate-patterns-library.ts --commit
